name: CI and CD
on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: apt-get install markdown
      - run: ./learn.sh
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: www
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
